server:
  port: 7001
spring:
  application:
    name: nacos-provider7001
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"