server:
  port: 9001
spring:
  application:
    name: sentinel9001
  cloud:
    nacos:
      discovery: #Nacos注册中心地址
        server-addr: localhost:8848
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719